# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - prefer_single_quotes
#     - camel_case_types

analyzer:
  exclude:
    - lib/src/**/*.g.dart
#   exclude:
#     - path/to/excluded/files/**
